import { Metadata } from 'next';
import s from './layout.module.scss';
import { Google } from '@/features/auth/google';
import { AuthSwitchText } from '@/features/auth-switch-text';
import { getLoggedInUser } from '@/shared/module/appwrite';
import { redirect } from 'next/navigation';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await getLoggedInUser();

  if (user) {
    redirect('/account');
  }
  return (
    <div className={s.authContent}>
      <div className={s.authContent__form}>
        <div className={s.authContent__content}>
          {children}{' '}
          <p className={s.hr}>
            <span>OR</span>
          </p>
          <Google />
          <AuthSwitchText />
        </div>
      </div>
      <div className={s.authContent__image}></div>
    </div>
  );
}
