import { Metadata } from 'next';
import s from './layout.module.scss';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className={s.authContent}>
      <div className={s.authContent__form}>{children}</div>
      <div className={s.authContent__image}></div>
    </div>
  );
}
