import { Metadata } from 'next';
import s from './layout.module.scss';
import { Google } from '@/features/auth/google';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className={s.authContent}>
      <div className={s.authContent__form}>
        <div className={s.authContent__content}>
          {children}{' '}
          <p className={s.hr}>
            <span>OR</span>{' '}
          </p>
          <Google />
        </div>
      </div>
      <div className={s.authContent__image}></div>
    </div>
  );
}
