import type { Metadata } from 'next';
import { StoreProvider } from './_providers/StoreProvider';
import { Lato } from 'next/font/google';
import './globals.css';
import './_styles/ui/index.scss';
import { TanstackProvider } from './_providers/TanstackProvider';
import { Header } from '@/widgets/header';

const lato = Lato({
  variable: '--font-family',
  subsets: ['latin'],
  weight: ['300', '400', '700', '900'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${lato.variable}`}>
        <StoreProvider>
          <TanstackProvider>
            <Header />
            {children}
          </TanstackProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
