export const POPULAR_GENRES = [
  'Fiction',
  'Nonfiction',
  'Fantasy',
  'Science Fiction',
  'Mystery',
  'Thriller',
  'Romance',
  'Historical',
  'Biography & Memoir',
  'Self-Help',
  'Health & Wellness',
  'Science',
  'History',
  'Art & Photography',
  'Travel',
  'Cooking / Food',
  "Children's Books",
  'Young Adult',
  'Religion & Spirituality',
  'Business & Economics',
];
